### ISSUE TITLE
Regression model, no result

### ISSUE THREAD

**Issue by nathanlim45** [uber/manifold#101]
#### Summary
I used Jupyter notebook and did the `Manifold example` without any problem. But when I try with the regression model, it doesn't show any result. I couldn't find any regression model example of this.

#### Expected Behavior
Works just like classification model

#### Current Behavior

`Manifold` doesn't return result for Regression model. even no error raised

#### Possible Solution

Any regression model example

**Comment by gnavvy** [comment]
Hi @nathanlim45,

Could you provide more details on how you tried the tool with your regression model?
Was it explicitly in the Jupyter environment that no results were shown? 
Or the regression example in the [web demo](http://manifold.mlvis.io/) didn't work for you either?

![image](https://user-images.githubusercontent.com/144743/72944541-0a5edb00-3d2e-11ea-92dc-fb58662e546c.png)

**Comment by kenns29** [comment]
@nathanlim45 I'm thinking of adding a regression example for the Jupyter binding. Give the following code snippet a try
```python
from mlvis import Manifold
import sys, json, math
import pandas as pd
from random import uniform, normalvariate
def generate_random_categorical_value(categories):
    return categories[int(math.floor(uniform(0, 1) * len(categories)))]
    
num_instances = 100
categories = ['A', 'B', 'C', 'D']
domain = [1, 1000]

x = [{'feature_0': math.floor(uniform(*domain)), 
      'feature_1': generate_random_categorical_value(categories)} 
     for i in range(0, num_instances)]

yPred = [pd.DataFrame([{'arbitrarily_name': normalvariate(i, 0.1 + i * 0.1)} for i in range(0, num_instances)]) for i in range(0, 3)]
yTrue = [normalvariate(0, 0.1) for i in range(0, num_instances)]
Manifold(props={'data': {
    'x': x,
    'yPred': yPred,
    'yTrue': yTrue
}})
```

**Comment by nathanlim45** [comment]
@kenns29 it worked. Thank you. The problem was that I put different format for `yPred`
