### ISSUE TITLE
CSV upload not working

### ISSUE THREAD

**Issue by alexbogun** [uber/manifold#103]
Neither Manifold running locally nor http://manifold.mlvis.io/ returns any result after uploading .csv feature, prediction and ground truths data sets.

I have tried following the [instructions ](https://github.com/uber/manifold#upload-csv-to-demo-app) on how to format .csv files, but it does not seem to work for me.

The csv files I have tried it with are attached (renamed extension to .txt, to be able to attach to issue).

What am I missing?

[truth.txt](https://github.com/uber/manifold/files/4134040/truth.txt)
[prediction.txt](https://github.com/uber/manifold/files/4134041/prediction.txt)
[features.txt](https://github.com/uber/manifold/files/4134042/features.txt)

**Comment by Casyfill** [comment]
same issue

**Comment by javidhsueh** [comment]
Let me investigate this

**Comment by Casyfill** [comment]
actually sorry, it worked for me once I've added column names for Ypred and Ytrue

**Comment by javidhsueh** [comment]
OK gotcha. I'll close this issue for now. Please reach out to us if you're still experiencing the same issue.

**Comment by alexbogun** [comment]
What did you do differently than in the attached 3 files, I have column names there as well? Please do not close this yet.

**Comment by gnavvy** [comment]
Hi @alexbogun, 

Currently the data I/O logic expects the input files to exclude the index column with an empty column name. Could you try removing the first column in your files, or adding the `index=False` flag if you are using pandas to prepare the input files?

I've created #106 to improve the data validation experience.

**Comment by alexbogun** [comment]
Hi @gnavvy ,

Thank you very much for your help, the issue where indeed the index columns.
Adding error message would indeed be a great improvement.
But if I may suggest also to modify the images in [section on preparing data](https://github.com/uber/manifold#upload-csv-to-demo-app), because I was sure I had to include index based on those.
Thanks again, I will close this one, since you started [#106](https://github.com/uber/manifold/issues/106)

**Comment by alexbogun** [comment]
Hi, sorry to have to bother you again, but now I cannot figure out how to upload multiple predictions, when I upload only one of the predictions it works, but when I upload both it does not...
Files used:
[prediction1.txt](https://github.com/uber/manifold/files/4138891/prediction1.txt)
[prediction2.txt](https://github.com/uber/manifold/files/4138892/prediction2.txt)
[truth.txt](https://github.com/uber/manifold/files/4138893/truth.txt)
[features.txt](https://github.com/uber/manifold/files/4138894/features.txt)

**Comment by Casyfill** [comment]
You need to add second prediction as second column in the first prediction
file

**Comment by alexbogun** [comment]
@Casyfill tried that, does not work either

**Comment by sar2160** [comment]
I have tried adding multiple predictions as well without success. When I upload two prediction csv with the same format / no index I get this error:

`Error: yPred[1][0] has a different shape than other element in yPred.
          Check your input data.`

I've verified both are the same shape however.

**Comment by Firenze11** [comment]
@sar2160 Could you share the files that caused the issues? And are you using the website or running the application locally?

**Comment by alexbogun** [comment]
Hi,

it does not work both locally and on the website.

The files are attached to the questions.

Best regards
Alex
