### ISSUE TITLE
Regression model in python, error 

### ISSUE THREAD

**Issue by prasiyer** [uber/manifold#108]
I am trying to use Manifold in jupyter notebook. My dataset consists of features, ground truth and predictions for 1 model. CSV files are attached. I get the following error -

yTrue must be a list/ndarray. 

I am able to get the results with the demo app.
[TestData_Results.zip](https://github.com/uber/manifold/files/4167881/TestData_Results.zip)

**Comment by kenns29** [comment]
@prasiyer please refer to https://github.com/uber/manifold/issues/101 for an example of using manifold in Jupyter with regression data.

**Comment by prasiyer** [comment]
Thank you. Changing the format for yPred made it work. 

The initial error message mentioned "yTrue must be a list/ndarray" while in reality issue was with yPred. Revising the error message would be helpful.

**Comment by kenns29** [comment]
@prasiyer thanks for pointing this out.

**Comment by Firenze11** [comment]
#106 is tracking the error message enhancement work; closing this task for now.
