### ISSUE TITLE
Jupyter notebook - Export Segmentation not working

### ISSUE THREAD

**Issue by prasiyer** [uber/manifold#109]
I am running Manifold from Jupyter notebook on Chrome browser.

Clicking on "Export Segmentation" button in the output widget outputs a list with the indexes of the input data. Is is possible to obtain the segment number. For example, Segment_1 or Segment_2 along with the index.

**Comment by kenns29** [comment]
@prasiyer can you specify the format you want. We don't support other output formats right now. If you want some specific format, you can write some transformation code.

**Comment by Firenze11** [comment]
The export button should export 2 lists, corresponding to segment-group-0 and segment-group-1 respectively. @prasiyer could you confirm there are two lists? If so then that is the currently supported format. We suggest you do some data transformation afterwards. If not, please comment.
