### ISSUE TITLE
Jupyter Binding: Dynamically Load React Component 

### ISSUE THREAD

**Issue by kenns29** [uber/manifold#46]
The Jupyter binding should enable dynamic loading of React component. This will allow the users to install custom React components into the mlvis library. This will also help to reduce the amount of boilerplate in the code.

A planned implementation would leverage a config file called "jrequirements.json" which is shared by both the Python and JS code. This file will specify the Python wrapper name and the corresponding JS module and widget customizations, along with other functionalities. These specifications will be used to dynamically generate the corresponding Python and JS code.

------------------------------------------

Dynamically generate widget frontend (https://github.com/uber/manifold/pull/47)
Mockup ext code for JS component widget extension (https://github.com/uber/manifold/pull/48)
Correctly handle jrequirements.json in Python (https://github.com/uber/manifold/pull/49)

**Comment by Firenze11** [comment]
This seems to be resolved. Closing.
