### ISSUE TITLE
Error on startup of example - Unknown option: base.rootMode

### ISSUE THREAD

**Issue by JensHumrich** [uber/manifold#97]
#### Summary
After following the code snippet, how to locally start the example, an error is thrown and the website remains blank.

#### Expected Behavior

Example website pops up.

#### Current Behavior
Upon startup an error message is thrown

`$ npm run start

> @ start /Users/jh186076/Documents/03_Privat/manifold/examples/manifold
> webpack-dev-server --progress --hot --open

10% building 1/1 modules 0 activeℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/jh186076/Documents/03_Privat/manifold/examples/manifold
40% building 15/16 modules 1 active /Users/jh186076/Documents/03_Privat/manifold/examples/manifold/node_modules/events/events.jsℹ ｢wdm｣: wait until bundle finished: /
✖ ｢wdm｣: Hash: d8e9b3efe73932330b3a
Version: webpack 4.41.2
Time: 1141ms
Built at: 01/13/2020 9:47:44 AM
     Asset       Size  Chunks                   Chunk Names
    app.js    377 KiB     app  [emitted]        app
app.js.map    427 KiB     app  [emitted] [dev]  app
index.html  184 bytes          [emitted]        
Entrypoint app = app.js app.js.map
[0] multi (webpack)-dev-server/client?http://localhost:8080 (webpack)/hot/dev-server.js ./src/main.js 52 bytes {app} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {app} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {app} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {app} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {app} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.89 KiB {app} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {app} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {app} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {app} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {app} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {app} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {app} [built]
[./node_modules/webpack/hot/log-apply-result.js] (webpack)/hot/log-apply-result.js 1.27 KiB {app} [built]
[./node_modules/webpack/hot/log.js] (webpack)/hot/log.js 1.34 KiB {app} [built]
[./src/main.js] 1.85 KiB {app} [built] [failed] [1 error]
    + 20 hidden modules

WARNING in EnvironmentPlugin - MAPBOX_ACCESS_TOKEN environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.

ERROR in ./src/main.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: [BABEL] /Users/jh186076/Documents/03_Privat/manifold/examples/manifold/src/main.js: Unknown option: base.rootMode. Check out http://babeljs.io/docs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options.
    at Logger.error (/Users/jh186076/Documents/03_Privat/manifold/examples/manifold/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/jh186076/Documents/03_Privat/manifold/examples/manifold/node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
    at OptionManager.init (/Users/jh186076/Documents/03_Privat/manifold/examples/manifold/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/jh186076/Documents/03_Privat/manifold/examples/manifold/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/jh186076/Documents/03_Privat/manifold/examples/manifold/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/jh186076/Documents/03_Privat/manifold/examples/manifold/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/jh186076/Documents/03_Privat/manifold/examples/manifold/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/jh186076/Documents/03_Privat/manifold/examples/manifold/node_modules/babel-loader/lib/index.js:173:20)
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/html-webpack-plugin/default_index.ejs] 376 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
ℹ ｢wdm｣: Failed to compile.
`
#### Context and Environment

npm version 6.13.4
node v12.14.1

#### Steps to Reproduce

yarn
cd examples/manifold
yarn
npm run start

**Comment by kenns29** [comment]
@JensHumrich we can't reproduce this error. But I suspect it may have something to do with webpack or babel versions (which is weird given that they are in the `package.json`). Can you do a `yarn list webpack webpack-dev-server webpack-cli` and tell us what versions you are using.

**Comment by JensHumrich** [comment]
@kenns29 
(base) jh186076@MUSJH186076-933 manifold (master) $ yarn list webpack webpack-dev-server webpack-cli
yarn list v1.21.1
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ webpack-cli@3.3.10
├─ webpack-dev-server@3.9.0
└─ webpack@4.41.2
✨  Done in 1.00s.

**Comment by kenns29** [comment]
@JensHumrich hmm, can you do `yarn list @babel/core`.

**Comment by JensHumrich** [comment]
(base) jh186076@MUSJH186076-933 manifold (master) $ yarn list @babel/core
yarn list v1.21.1
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ @babel/core@7.7.4
✨  Done in 0.99s.

**Comment by JensHumrich** [comment]
I deleted all from the subfolder 
/node_modules
/example/manifold/node_modules

and rerun the appropiate ayrn commands. Now it seems to be working @kenns29 Thanks for your support.
